### PR TITLE
Upgrading to scala 2.13

### PR DESCRIPTION
**Pull request by johnspaul**
#7

### CODE REVIEW

**Comment by FunFunFine** [comment]
@dwickern can we have an update on this?

**Comment by aukgit** [comment]
@dwickern can you please push it???

**Comment by aukgit** [comment]
Thank you @dwickern

**Comment by dwickern** [comment]
Sorry for the delay. It's published as version 2.0.0

**Comment by aukgit** [comment]
Superb. 

Happy to catch up. Great feature btw, I am from C# and really appreciate this.

**Pull request merged**
